[theme]
base="dark"
primaryColor="#900C3F"         # Rouge Foncé (utilisé pour les boutons, liens)
backgroundColor="#1A531A"      # Vert Foncé (utilisé pour le fond principal)
secondaryBackgroundColor="#2E8B57" # Vert Forêt (pour la barre latérale)
textColor="#FFFFFF"            # Texte : Blanc
font="sans serif"
